export const GUIDE_ISSUES = [
  {
    id: "maker-install-001",
    deskId: "maker",
    desk: "Maker Edition",
    icon: "⌘",
    issue: "INSTALL",
    date: "AUG 28 · 2026",
    publishedAt: "2026-08-28T20:30:00.000Z",
    color: "#ff9466",
    title: "Install Velvet Signal on Your Laptop",
    kicker: "From zero to a local model with a durable, user-approved patch ledger.",
    dek: "A plain-language setup guide for Git, Node, Ollama, the local embedding model, patch release, retrieval inspection, and your first memory-assisted local-model question.",
    readTime: "6 min setup",
    validity: "90 days",
    expires: "2026-11-26",
    confidence: "Verified setup path",
    scope: "Local installation",
    editorial: [
      "Start with three tools: Git, Node.js 22 or newer, and Ollama. On Windows, Node can be installed with winget install OpenJS.NodeJS.LTS. After installation, reopen PowerShell and check node -v, npm.cmd -v, git --version, and ollama --version. If PowerShell blocks npm.ps1, use npm.cmd; changing the execution policy is not required.",
      "Download Velvet Signal from your user folder with git clone https://github.com/TONZHub/Velvet_Signal.git, enter the Velvet_Signal folder, and—while the local bridge is still under review—run git switch codex/local-rag-ollama. Then run npm.cmd install on Windows or npm install on macOS/Linux. npm must be run from inside the repository: if it tries C:\\Windows\\System32 or cannot find package.json in your home directory, change into Velvet_Signal first.",
      "Next, prepare local retrieval with ollama pull embeddinggemma and pull any Ollama chat model you want to use. Release a publication patch explicitly with npm.cmd run local -- release pantry-003, then inspect what the retrieval layer selected with npm.cmd run local -- inspect \"I cooked chicken five days ago and kept it refrigerated. It smells fine. Can I eat it?\". The local ledger is stored outside the repository at ~/.velvet-signal/patches.json, so it survives terminal and application restarts.",
      "Finally, ask a local model through the bridge with npm.cmd run local -- ask --model <your-model> \"your question\". Velvet Signal retrieves only active, approved claims, removes explicitly superseded claims before ranking, preserves patch/claim/source provenance, and injects a focused context block into the current user turn. Your question goes to the configured local Ollama server; the hosted publication is contacted only when you explicitly release a public patch.",
    ],
    pullquote: "The model does not have to remember the world. Velvet Signal remembers what changed.",
    sources: [
      { id: "MEI-SRC-1", name: "Velvet Signal repository", publisher: "GitHub", url: "https://github.com/TONZHub/Velvet_Signal", checked: "2026-08-28" },
      { id: "MEI-SRC-2", name: "Download Node.js", publisher: "Node.js", url: "https://nodejs.org/en/download", checked: "2026-08-28" },
      { id: "MEI-SRC-3", name: "Download Ollama on Windows", publisher: "Ollama", url: "https://ollama.com/download/windows", checked: "2026-08-28" },
      { id: "MEI-SRC-4", name: "EmbeddingGemma", publisher: "Ollama", url: "https://ollama.com/library/embeddinggemma", checked: "2026-08-28" },
    ],
    claims: [
      { id: "MEI-01", claim: "Velvet Signal's local bridge requires Node.js 22 or newer and can use npm.cmd on Windows when PowerShell blocks npm.ps1.", source: 0, sourceIds: ["MEI-SRC-1"], status: "verified" },
      { id: "MEI-02", claim: "The local bridge uses Ollama's embeddinggemma model for semantic retrieval by default and falls back to lexical retrieval when embeddings are unavailable.", source: 3, sourceIds: ["MEI-SRC-4", "MEI-SRC-1"], status: "verified" },
      { id: "MEI-03", claim: "Released patches are stored in a user-controlled local ledger outside the repository and are re-retrieved at inference time rather than written into model weights.", source: 0, sourceIds: ["MEI-SRC-1"], status: "architecture" },
      { id: "MEI-04", claim: "Only delivered, approved, unexpired, non-superseded claims participate in active local retrieval.", source: 0, sourceIds: ["MEI-SRC-1"], status: "retrieval rule" },
    ],
    toneNotes: [
      "Assume the reader may never have used npm or cloned a repository before.",
      "Do not instruct Windows users to run the project as Administrator just to bypass a directory or PowerShell error.",
    ],
    tags: ["makers", "install", "ollama", "local llm", "rag"],
  },
];
