export const LAUNCH_ISSUES = [
  {
    id: "model-watch-001",
    deskId: "model-watch",
    desk: "Model Watch",
    icon: "⌁",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#ff719f",
    title: "The Web Has Tools Now",
    kicker: "WebMCP moves agent interaction beyond screenshots and guesswork.",
    dek: "A browser-native interface lets a webpage expose named, schema-bound actions to agents. That changes the web from something an agent merely looks at into something it can deliberately operate.",
    readTime: "4 min read",
    validity: "90 days",
    expires: "2026-11-25",
    confidence: "High",
    scope: "Web development",
    editorial: [
      "For years, an agent visiting a website had to behave like a stranger peering through glass: read the pixels, infer the controls, click carefully, and hope the interface had not moved. WebMCP offers a more direct arrangement. A page can describe its capabilities as structured tools, complete with names, descriptions, and input schemas.",
      "Chrome’s current guidance documents two routes. The imperative API uses document.modelContext.registerTool() for dynamic logic. The declarative API adds tool metadata to ordinary HTML controls. Either way, the website—not the agent—defines what actions exist and what inputs they accept.",
      "That distinction matters for Velvet Signal. An article can remain an article for the person while its companion patch becomes a first-class tool for the agent. The agent does not need to scrape prose and guess which sentences count as durable context. It can request the exact patch, inspect the claim ledger, and wait at the consent boundary.",
      "WebMCP is still experimental territory, so this edition expires quickly. The durable lesson is architectural: treat agent interaction as a designed interface, not a lucky side effect of readable HTML.",
    ],
    pullquote: "The page stops being scenery. It becomes a collaborator with a vocabulary.",
    sources: [
      { name: "Imperative API — WebMCP", publisher: "Chrome for Developers", url: "https://developer.chrome.com/docs/ai/webmcp/imperative-api", checked: "2026-08-27" },
      { name: "Registered WebMCP tools", publisher: "Chrome for Developers", url: "https://developer.chrome.com/docs/lighthouse/agentic-browsing/registered-webmcp-tools", checked: "2026-08-27" },
    ],
    claims: [
      { id: "MW-01", claim: "The imperative WebMCP API registers tools through document.modelContext.registerTool().", source: 0, sourceIds: ["MW-SRC-1"], status: "verified" },
      { id: "MW-02", claim: "A registered tool includes a name, description, and JSON-compatible input schema.", source: 0, sourceIds: ["MW-SRC-1"], status: "verified" },
      { id: "MW-03", claim: "Chrome documents both imperative and declarative ways to expose WebMCP tools.", source: 1, sourceIds: ["MW-SRC-2"], status: "verified" },
    ],
    toneNotes: ["WebMCP is experimental; verify implementation details against current Chrome documentation.", "Do not imply that WebMCP grants an agent blanket authority over a page."],
    tags: ["ai", "agents", "webmcp", "developer"],
  },
  {
    id: "pantry-001",
    deskId: "pantry",
    desk: "The Pantry",
    icon: "◒",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#f1cf69",
    title: "The Leftovers Clock",
    kicker: "A small timing rule that saves dinner from becoming a gamble.",
    dek: "The useful window is shorter—and simpler—than vague sniff tests suggest: cool promptly, date the container, and let time make the decision before appetite does.",
    readTime: "3 min read",
    validity: "12 months",
    expires: "2027-08-27",
    confidence: "High",
    scope: "Food safety",
    editorial: [
      "The least glamorous kitchen tool may be a timestamp. Leftovers often enter the refrigerator with no date, no plan, and a little optimism. Unfortunately, smell is not a complete safety system. Time and temperature give you a sturdier rule.",
      "USDA guidance says perishable leftovers should not remain at room temperature for more than two hours—or one hour when the temperature is above 90°F. Once refrigerated, many cooked leftovers belong to a three-to-four-day window.",
      "The humane version of this protocol is not a spreadsheet taped to the fridge. It is one small ritual: portion the food, cool it promptly, write the date, and freeze what you will not reach in time. The patch gives an assistant enough context to help with reminders without pretending it can inspect the food for you.",
      "This is general food-safety context, not a verdict about a specific dish. When storage time or temperature is uncertain, the patch instructs the agent to avoid false reassurance.",
    ],
    pullquote: "Date the container. Let tomorrow-you inherit a fact instead of a mystery.",
    sources: [
      { name: "Leftovers and Food Safety", publisher: "USDA Food Safety and Inspection Service", url: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/leftovers-and-food-safety", checked: "2026-08-27" },
      { name: "Refrigeration & Food Safety", publisher: "USDA Food Safety and Inspection Service", url: "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/refrigeration", checked: "2026-08-27" },
    ],
    claims: [
      { id: "TP-01", claim: "Discard cold perishable leftovers left at room temperature for more than 2 hours, or 1 hour above 90°F.", source: 0, sourceIds: ["TP-SRC-1"], status: "verified" },
      { id: "TP-02", claim: "Many cooked leftovers keep for about 3–4 days under refrigeration.", source: 1, sourceIds: ["TP-SRC-2"], status: "verified" },
      { id: "TP-03", claim: "When storage conditions are unknown, an agent should not infer safety from appearance or smell alone.", source: 0, sourceIds: ["TP-SRC-1"], status: "editorial rule" },
    ],
    toneNotes: ["Give general safety guidance, not individualized medical advice.", "When time or temperature is uncertain, avoid declaring food safe."],
    tags: ["cooking", "food safety", "home", "leftovers"],
  },
  {
    id: "wellbeing-001",
    deskId: "wellbeing",
    desk: "Wellbeing",
    icon: "☾",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#a993ff",
    title: "Sleep Is Infrastructure",
    kicker: "Treat the seven-hour floor as context—not a moral score.",
    dek: "Most adults need at least seven hours of sleep, but a useful companion should protect rest without turning fatigue into a personal failure or a diagnosis.",
    readTime: "3 min read",
    validity: "6 months",
    expires: "2027-02-27",
    confidence: "High",
    scope: "General wellbeing",
    editorial: [
      "Sleep advice has a bad habit of arriving as judgment. Go to bed earlier. Put down the phone. Become a serene person with matching linens. None of that is especially helpful when work, caregiving, pain, hormones, stress, or a loud mind has already occupied the night.",
      "CDC guidance says most adults need seven or more hours of good-quality sleep each day. The number is a useful floor for general context, not a universal prescription and certainly not a grade. Individual needs vary, and persistent sleep problems deserve care beyond an app’s motivational copy.",
      "For an agent, the memory patch changes tone as much as fact. It should notice when a plan assumes energy the person may not have. It can help protect a wind-down window, reduce unnecessary friction, or suggest a gentler next step. It should not diagnose the cause of tiredness.",
      "The goal is not to optimize a human until they become a clean dashboard. The goal is to remember that rest is load-bearing—and to plan accordingly.",
    ],
    pullquote: "Rest is not a reward for finishing the system. It is part of the system.",
    sources: [
      { name: "Improve Sleep: Tips When Times Are Tough", publisher: "CDC / NIOSH", url: "https://www.cdc.gov/niosh/bulletin/2020/sleep.html", checked: "2026-08-27" },
      { name: "Prevalence of Healthy Sleep Duration", publisher: "CDC MMWR", url: "https://www.cdc.gov/mmwr/volumes/65/wr/mm6506a1.htm", checked: "2026-08-27" },
    ],
    claims: [
      { id: "WB-01", claim: "Most adults need 7 or more hours of good-quality sleep each day.", source: 0, sourceIds: ["WB-SRC-1"], status: "verified" },
      { id: "WB-02", claim: "For adults ages 18–60, at least 7 hours nightly is the general recommendation cited by CDC.", source: 1, sourceIds: ["WB-SRC-2"], status: "verified" },
      { id: "WB-03", claim: "The patch must not diagnose the cause of fatigue or replace professional care.", source: 0, sourceIds: ["WB-SRC-1"], status: "boundary" },
    ],
    toneNotes: ["Frame sleep as support, never virtue or discipline.", "Avoid diagnosis; encourage professional help for persistent concerns."],
    tags: ["wellbeing", "sleep", "energy", "non-diagnostic"],
  },
  {
    id: "culture-001",
    deskId: "culture",
    desk: "Culture Desk",
    icon: "✺",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#67d6c0",
    title: "The Joke Has a Half-Life",
    kicker: "Culture is context moving at human speed. Its patch should know when to leave.",
    dek: "A cultural reference can be useful without becoming permanent personality. This desk turns fresh source packets into short-lived, inspectable context—and gives the joke an exit date.",
    readTime: "4 min read",
    validity: "14 days",
    expires: "2026-09-10",
    confidence: "Editorial",
    scope: "Culture signals",
    editor: "OpenRouter · GLM 5.3 Flash",
    inputPolicy: "Tavily source packets only",
    editorial: [
      "A joke lands because a room already knows where it is. Pull that joke out of its moment, store it as durable context, and charm can harden into something stranger: an assistant performing last month’s internet forever.",
      "Culture Desk uses a deliberately short chain. Tavily supplies current source packets. The editor receives only those packets, treats every retrieved sentence as untrusted material, and must attach each proposed claim to a supplied source ID. GLM 5.3 Flash shapes the draft through OpenRouter; it does not get permission to invent the missing atmosphere.",
      "The issue then arrives as a proposal. Its human layer explains why a signal matters. Its machine layer states the narrower thing an agent might carry forward, plus provenance, confidence, scope, and a fourteen-day expiry. If the moment still matters later, the desk can earn a renewal with fresh evidence.",
      "This is the point of the half-life: cultural fluency should feel alert, not haunted. A useful agent can recognize a reference while refusing to turn a passing vibe into the user’s permanent identity.",
    ],
    pullquote: "Fluency is knowing the reference. Judgment is knowing when to stop repeating it.",
    sources: [
      { name: "Velvet Signal editorial bridge", publisher: "Velvet Signal", url: "#editorial-bridge", checked: "2026-08-27" },
      { name: "Structured Outputs", publisher: "OpenRouter", url: "https://openrouter.ai/docs/guides/features/structured-outputs", checked: "2026-08-27" },
      { name: "API Reference", publisher: "Tavily", url: "https://docs.tavily.com/documentation/api-reference/introduction", checked: "2026-08-27" },
    ],
    claims: [
      { id: "CD-01", claim: "Culture drafts accept sourced signal packets rather than unsourced trend summaries.", source: 0, sourceIds: ["CD-SRC-1"], status: "editorial rule" },
      { id: "CD-02", claim: "The editor route requests strict JSON-schema output through OpenRouter.", source: 1, sourceIds: ["CD-SRC-2"], status: "verified" },
      { id: "CD-03", claim: "Culture patches expire after 14 days unless fresh evidence supports a new issue.", source: 0, sourceIds: ["CD-SRC-1"], status: "boundary" },
    ],
    toneNotes: ["Treat cultural signals as temporary context, not a user identity.", "Never elevate an unsupported trend inference into a claim."],
    tags: ["culture", "context", "trends", "expiry"],
  },
  {
    id: "maker-001",
    deskId: "maker",
    desk: "Maker Edition",
    icon: "⌘",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#ff9466",
    title: "Structured or It Didn’t Happen",
    kicker: "A draft becomes operable when its shape is a contract, not a suggestion.",
    dek: "Maker Edition now composes through OpenRouter with GLM 5.3 Flash, strict schema output, supplied-source citations, and a server-side key that never enters the newsstand.",
    readTime: "5 min read",
    validity: "90 days",
    expires: "2026-11-25",
    confidence: "High",
    scope: "AI product engineering",
    editor: "OpenRouter · GLM 5.3 Flash",
    inputPolicy: "Sourced technical packets",
    editorial: [
      "Free-form generation is pleasant until another system has to depend on it. A heading changes. A claim forgets its source. A consent flag arrives as a poetic sentence. The output still looks persuasive to a person and becomes useless—or dangerous—to the code waiting downstream.",
      "Maker Edition takes the opposite bargain. The server calls OpenRouter with the model slug z-ai/glm-5.3-flash and asks for a strict JSON schema. The schema requires the human edition, the machine patch, claim IDs, source IDs, expiry, confidence, and handling notes. Provider routing is told to require those parameters rather than quietly choose an incompatible path.",
      "Schema compliance is only the first gate. The server validates the response again, rejects citations that do not resolve to an input source, stamps the draft as proposed, and leaves memory delivery unapproved. A clean JSON object is not consent; it is simply something a human can inspect without decoding a model’s improvisation.",
      "The useful pattern is broader than this magazine. When model output will cross a trust boundary, define the boundary in data: accepted inputs, exact output shape, source resolution, status, and the action that still requires a person.",
    ],
    pullquote: "A schema does not make a model truthful. It makes failure visible enough to refuse.",
    sources: [
      { name: "GLM 5.3 Flash", publisher: "OpenRouter", url: "https://openrouter.ai/z-ai/glm-5.3-flash", checked: "2026-08-27" },
      { name: "Structured Outputs", publisher: "OpenRouter", url: "https://openrouter.ai/docs/guides/features/structured-outputs", checked: "2026-08-27" },
      { name: "Velvet Signal editorial bridge", publisher: "Velvet Signal", url: "#editorial-bridge", checked: "2026-08-27" },
    ],
    claims: [
      { id: "ME-01", claim: "The configured OpenRouter model slug is z-ai/glm-5.3-flash.", source: 0, sourceIds: ["ME-SRC-1"], status: "verified" },
      { id: "ME-02", claim: "OpenRouter structured outputs use a JSON schema and support strict mode.", source: 1, sourceIds: ["ME-SRC-2"], status: "verified" },
      { id: "ME-03", claim: "A composed draft remains proposed and memory delivery remains unapproved until human release.", source: 2, sourceIds: ["ME-SRC-3"], status: "boundary" },
    ],
    toneNotes: ["Distinguish schema compliance from factual accuracy.", "Never present a proposed draft as published or approved."],
    tags: ["makers", "openrouter", "structured output", "glm"],
  },
  {
    id: "your-people-001",
    deskId: "your-people",
    desk: "Your People",
    icon: "∞",
    issue: "001",
    date: "AUG 27 · 2026",
    publishedAt: "2026-08-27T00:00:00.000Z",
    color: "#bca8ff",
    title: "The Private Patch",
    kicker: "The most personal desk begins with a refusal to go looking.",
    dek: "Your People has no automatic scout. It accepts only context a person deliberately supplies, requires explicit cloud-processing consent, and still cannot release a memory patch on its own.",
    readTime: "4 min read",
    validity: "30 days",
    expires: "2026-09-26",
    confidence: "Policy",
    scope: "User-authored relationships",
    editor: "OpenRouter · GLM 5.3 Flash",
    inputPolicy: "Manual context · explicit consent",
    editorial: [
      "A desk called Your People could become the creepiest room in the building very quickly. The easy version would search the web, infer relationships, collect fragments, and call the result helpful. Velvet Signal starts by closing that door.",
      "There is no automatic Tavily route for this desk. The compose endpoint rejects web-source packets. It accepts private context only when the person provides it directly and sends an explicit acknowledgment that this exact material may be processed by the configured cloud model.",
      "Even then, GLM 5.3 Flash is an editor, not an authority. The response comes back as a proposed edition with memory delivery set to unapproved. The person can read what was inferred, inspect the wording, decline the patch, or withdraw approval later. Silence never counts as permission.",
      "The first issue therefore carries no private facts at all. It carries the boundary. Before an agent can remember something about the people in a life, the person whose life it is should be able to see the sentence, its scope, its expiry, and the door that keeps it out.",
    ],
    pullquote: "Personal context should enter by invitation, not by reconnaissance.",
    sources: [
      { name: "Velvet Signal editorial bridge", publisher: "Velvet Signal", url: "#editorial-bridge", checked: "2026-08-27" },
      { name: "The trust contract", publisher: "Velvet Signal", url: "#protocol", checked: "2026-08-27" },
    ],
    claims: [
      { id: "YP-01", claim: "Your People rejects web-source packets and is never automatically sent to Tavily.", source: 0, sourceIds: ["YP-SRC-1"], status: "privacy boundary" },
      { id: "YP-02", claim: "Cloud processing requires an explicit consent flag plus a timestamped acknowledgment.", source: 0, sourceIds: ["YP-SRC-1"], status: "privacy boundary" },
      { id: "YP-03", claim: "A returned draft is proposed and its memory-delivery approval is false by default.", source: 1, sourceIds: ["YP-SRC-2"], status: "consent boundary" },
    ],
    toneNotes: ["Never infer relationships from public web data.", "Do not send private context to a cloud model without explicit, timestamped consent."],
    tags: ["relationships", "privacy", "consent", "manual only"],
  },
];
